### ISSUE TITLE
Please add a explicit License

### ISSUE THREAD

**Issue by yeikel** [check-spelling/check-spelling-action#1]
As stated in the title of this issue, please add an explicit license under the root directory of the project called "LICENSE" (no extension)

**Comment by yeikel** [comment]
> This isn't the thing you're looking for. The action is licensed under https://github.com/check-spelling/check-spelling/blob/main/LICENSE.txt
> 
> This is just for the [website](https://www.check-spelling.dev/).
> 
> I can't imagine someone wanting to fork the website, but if you want to make a contribution, I'm happy to adjust...

Ah. Thanks for clarifying. The name of the repo confused me

**Comment by jsoref** [comment]
I've added a description to the About section on the root page and removed some other fields which should help some.
